-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 19:55:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `idAnimal` INT NOT NULL,
  `nomeAnimal` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `origem` VARCHAR(45) NULL,
  `brinco` INT NULL,
  `sexo` ENUM('F', 'M') NULL,
  `raca` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnimal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pesagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pesagem` (
  `idPesagem` INT NOT NULL,
  `peso` FLOAT NULL,
  `dataPesagem` DATE NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idPesagem`, `Animal_idAnimal`),
  INDEX `fk_Pesagem_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Pesagem_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descarte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descarte` (
  `idDescarte` INT NOT NULL,
  `motivo` VARCHAR(45) NULL,
  `causa` VARCHAR(255) NULL,
  `dataDescarte` DATE NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idDescarte`, `Animal_idAnimal`),
  INDEX `fk_Descarte_Animal_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Descarte_Animal`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicacao` (
  `idMedicacao` INT NOT NULL,
  `nomePatologia` VARCHAR(45) NULL,
  `nomeMedicamento` VARCHAR(45) NULL,
  `dataMedicacao` DATE NULL,
  `dataLiberacao` DATE NULL,
  `Observacao` VARCHAR(255) NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idMedicacao`, `Animal_idAnimal`),
  INDEX `fk_Medicacao_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Medicacao_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `idConsulta` INT NOT NULL,
  `nomeConsulta` VARCHAR(45) NULL,
  `dataConsulta` VARCHAR(45) NULL,
  `descricaoConsulta` VARCHAR(255) NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idConsulta`, `Animal_idAnimal`),
  INDEX `fk_Consulta_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL,
  `nomeEvento` VARCHAR(45) NULL,
  `dataEvento` DATE NULL,
  `dataProximoEvento` DATE NULL,
  `descricaoEvento` VARCHAR(255) NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `Animal_idAnimal`),
  INDEX `fk_Evento_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenhaDiaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenhaDiaria` (
  `idOrdenhaDiaria` INT NOT NULL,
  `qtdeLitros` FLOAT NULL,
  `nrFemeas` INT NULL,
  `dataOrdenhaDiaria` DATE NULL,
  PRIMARY KEY (`idOrdenhaDiaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pai` (
  `Animal_idAnimal` INT NOT NULL,
  `Animal_idAnimal1` INT NOT NULL,
  PRIMARY KEY (`Animal_idAnimal`, `Animal_idAnimal1`),
  INDEX `fk_Pai_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  INDEX `fk_Pai_Animal2_idx` (`Animal_idAnimal1` ASC) VISIBLE,
  CONSTRAINT `fk_Pai_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pai_Animal2`
    FOREIGN KEY (`Animal_idAnimal1`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mae` (
  `Animal_idAnimal` INT NOT NULL,
  `Animal_idAnimal1` INT NOT NULL,
  PRIMARY KEY (`Animal_idAnimal`, `Animal_idAnimal1`),
  INDEX `fk_Mae_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  INDEX `fk_Mae_Animal2_idx` (`Animal_idAnimal1` ASC) VISIBLE,
  CONSTRAINT `fk_Mae_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mae_Animal2`
    FOREIGN KEY (`Animal_idAnimal1`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
